In [2]:
import pandas as pd

# Base path to your files (Windows path)
base_path = r"D:\ML\ML_projects\CreditPathAI\Microsoft_Loan_Data\\"

# Read each file
df_borrower = pd.read_csv(base_path + "Borrower.txt", sep='\t')
df_borrower_prod = pd.read_csv(base_path + "Borrower_Prod.txt", sep='\t')
df_loan = pd.read_csv(base_path + "Loan.txt", sep='\t')
df_loan_prod = pd.read_csv(base_path + "Loan_Prod.txt", sep='\t')

# Quick check
print(df_borrower.head())
print(df_loan.head())

   memberId residentialState yearsEmployment homeOwnership  annualIncome  \
0   2305095               NM       10+ years          rent         56471   
1   2610493               WA       2-5 years          rent         55038   
2   2491679               MS        < 1 year          rent         56610   
3   2092798               TX       6-9 years           own         54887   
4   2633077               MA       2-5 years          rent         53522   

   incomeVerified  dtiRatio  lengthCreditHistory  numTotalCreditLines  \
0               1     16.80                    6                   11   
1               0     19.99                   22                    8   
2               1     14.33                    5                    8   
3               1     14.80                   12                   14   
4               1     10.14                    4                   21   

   numOpenCreditLines  numOpenCreditLines1Year  revolvingBalance  \
0                 9.0               

In [3]:
df = pd.merge(df_borrower, df_loan, on='memberId', how='inner')

print("Merged DataFrame (first 5 rows):")
display(df.head())

print("\nMerged DataFrame Info:")
df.info()

print("\nShape of the merged DataFrame:")
print(df.shape)
     

Merged DataFrame (first 5 rows):


,memberId,residentialState,yearsEmployment,homeOwnership,annualIncome,incomeVerified,dtiRatio,lengthCreditHistory,numTotalCreditLines,numOpenCreditLines,...,loanId,date,purpose,isJointApplication,loanAmount,term,interestRate,monthlyPayment,grade,loanStatus
0,2305095,NM,10+ years,rent,56471,1,16.80,6,11,9.0,...,1888978,12/10/2014,debtconsolidation,0.0,25190.0,60 months,6.25,490,E3,Current
1,2610493,WA,2-5 years,rent,55038,0,19.99,22,8,7.0,...,1299695,9/15/2014,debtconsolidation,0.0,21189.0,60 months,10.49,455,B3,Current
2,2491679,MS,< 1 year,rent,56610,1,14.33,5,8,5.0,...,1875016,9/11/2014,debtconsolidation,0.0,29908.0,60 months,9.11,622,B2,Current
3,2092798,TX,6-9 years,own,54887,1,14.80,12,14,7.0,...,1440478,4/22/2016,homeimprovement,0.0,13053.0,48 months,11.89,343,B3,Current
4,2633077,MA,2-5 years,rent,53522,1,10.14,4,21,19.0,...,1124634,2/3/2016,debtconsolidation,0.0,24613.0,60 months,15.13,587,A3,Current



Merged DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   memberId                  100000 non-null  int64  
 1   residentialState          100000 non-null  object 
 2   yearsEmployment           100000 non-null  object 
 3   homeOwnership             100000 non-null  object 
 4   annualIncome              100000 non-null  int64  
 5   incomeVerified            100000 non-null  int64  
 6   dtiRatio                  100000 non-null  float64
 7   lengthCreditHistory       100000 non-null  int64  
 8   numTotalCreditLines       100000 non-null  int64  
 9   numOpenCreditLines        99033 non-null   float64
 10  numOpenCreditLines1Year   100000 non-null  int64  
 11  revolvingBalance          100000 non-null  int64  
 12  revolvingUtilizationRate  100000 non-null  float64
 13  numDerogatoryRec     

In [4]:
df.drop(['memberId', 'loanId'], axis=1, inplace=True)
print("Columns after dropping 'memberId' and 'loanId':")
display(df.columns)

Columns after dropping 'memberId' and 'loanId':


Index(['residentialState', 'yearsEmployment', 'homeOwnership', 'annualIncome',
       'incomeVerified', 'dtiRatio', 'lengthCreditHistory',
       'numTotalCreditLines', 'numOpenCreditLines', 'numOpenCreditLines1Year',
       'revolvingBalance', 'revolvingUtilizationRate', 'numDerogatoryRec',
       'numDelinquency2Years', 'numChargeoff1year', 'numInquiries6Mon', 'date',
       'purpose', 'isJointApplication', 'loanAmount', 'term', 'interestRate',
       'monthlyPayment', 'grade', 'loanStatus'],
      dtype='object')

In [5]:
df.isnull().sum()

residentialState               0
yearsEmployment                0
homeOwnership                  0
annualIncome                   0
incomeVerified                 0
dtiRatio                       0
lengthCreditHistory            0
numTotalCreditLines            0
numOpenCreditLines           967
numOpenCreditLines1Year        0
revolvingBalance               0
revolvingUtilizationRate       0
numDerogatoryRec               0
numDelinquency2Years           0
numChargeoff1year              0
numInquiries6Mon               0
date                           0
purpose                        0
isJointApplication           971
loanAmount                  1006
term                        1071
interestRate                   0
monthlyPayment                 0
grade                          0
loanStatus                     0
dtype: int64

In [6]:
for col in df.columns:
  print(f" {col}, ----- {df[col].dtype}")

 residentialState, ----- object
 yearsEmployment, ----- object
 homeOwnership, ----- object
 annualIncome, ----- int64
 incomeVerified, ----- int64
 dtiRatio, ----- float64
 lengthCreditHistory, ----- int64
 numTotalCreditLines, ----- int64
 numOpenCreditLines, ----- float64
 numOpenCreditLines1Year, ----- int64
 revolvingBalance, ----- int64
 revolvingUtilizationRate, ----- float64
 numDerogatoryRec, ----- int64
 numDelinquency2Years, ----- int64
 numChargeoff1year, ----- int64
 numInquiries6Mon, ----- int64
 date, ----- object
 purpose, ----- object
 isJointApplication, ----- float64
 loanAmount, ----- float64
 term, ----- object
 interestRate, ----- float64
 monthlyPayment, ----- int64
 grade, ----- object
 loanStatus, ----- object


In [7]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df.drop('loanStatus', axis=1)
y = df['loanStatus']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (80000, 24)
Shape of X_test: (20000, 24)
Shape of y_train: (80000,)
Shape of y_test: (20000,)


In [8]:
from sklearn.impute import SimpleImputer

numerical_cols_with_nulls = ['numOpenCreditLines', 'isJointApplication', 'loanAmount']
categorical_cols_with_nulls = ['term']

# Numerical imputer
num_imputer = SimpleImputer(strategy='median')
X_train[numerical_cols_with_nulls] = num_imputer.fit_transform(X_train[numerical_cols_with_nulls])
X_test[numerical_cols_with_nulls] = num_imputer.transform(X_test[numerical_cols_with_nulls])

# Categorical imputer
cat_imputer = SimpleImputer(strategy='most_frequent')
X_train[categorical_cols_with_nulls] = cat_imputer.fit_transform(X_train[categorical_cols_with_nulls])
X_test[categorical_cols_with_nulls] = cat_imputer.transform(X_test[categorical_cols_with_nulls])

##### ENCODING

In [9]:
threshold = 2000

state_counts = X_train['residentialState'].value_counts()

# We create a list of the states that meet our threshold.
top_states = state_counts[state_counts >= threshold].index.tolist()

print(f"Found {len(top_states)} states with counts >= {threshold} in X_train.")
print("These will be kept:", top_states)
print("-" * 30)

print("Applying binning to X_train...")
X_train['residentialState'] = X_train['residentialState'].apply(lambda x: x if x in top_states else 'Other')

print("Applying the same binning rule to X_test...")
X_test['residentialState'] = X_test['residentialState'].apply(lambda x: x if x in top_states else 'Other')



print("\nNew category counts in X_train['residentialState']:")
print(X_train['residentialState'].value_counts())

print("\nNew category counts in X_test['residentialState']:")
print(X_test['residentialState'].value_counts())

Found 10 states with counts >= 2000 in X_train.
These will be kept: ['CA', 'FL', 'DC', 'NY', 'TX', 'WA', 'IA', 'IL', 'IN', 'ID']
------------------------------
Applying binning to X_train...
Applying the same binning rule to X_test...

New category counts in X_train['residentialState']:
residentialState
Other    45951
CA        5597
FL        5257
DC        4292
NY        4125
TX        2760
WA        2758
IA        2395
IL        2376
IN        2246
ID        2243
Name: count, dtype: int64

New category counts in X_test['residentialState']:
residentialState
Other    11390
CA        1460
FL        1346
DC        1104
NY        1036
WA         719
TX         672
ID         602
IA         580
IN         554
IL         537
Name: count, dtype: int64


In [10]:
def engineer_date_features(df):
    """Converts 'date' column to datetime and extracts features."""

    df_copy = df.copy()


    df_copy['date'] = pd.to_datetime(df_copy['date'], format='%m/%d/%Y')

    df_copy['loan_issue_year'] = df_copy['date'].dt.year
    df_copy['loan_issue_month'] = df_copy['date'].dt.month
    df_copy['loan_issue_dayofweek'] = df_copy['date'].dt.dayofweek # Monday=0, Sunday=6

    df_copy = df_copy.drop('date', axis=1)

    return df_copy

In [11]:
#  Apply the function to both X_train and X_test ---
print("Processing date features for X_train...")
X_train = engineer_date_features(X_train)

print("Processing date features for X_test...")
X_test = engineer_date_features(X_test)


print("\nNew date features created. X_train columns:")
print(X_train.columns)
print("\nFirst 5 rows with new features:")
print(X_train[['loan_issue_year', 'loan_issue_month', 'loan_issue_dayofweek']].head())

Processing date features for X_train...
Processing date features for X_test...

New date features created. X_train columns:
Index(['residentialState', 'yearsEmployment', 'homeOwnership', 'annualIncome',
       'incomeVerified', 'dtiRatio', 'lengthCreditHistory',
       'numTotalCreditLines', 'numOpenCreditLines', 'numOpenCreditLines1Year',
       'revolvingBalance', 'revolvingUtilizationRate', 'numDerogatoryRec',
       'numDelinquency2Years', 'numChargeoff1year', 'numInquiries6Mon',
       'purpose', 'isJointApplication', 'loanAmount', 'term', 'interestRate',
       'monthlyPayment', 'grade', 'loan_issue_year', 'loan_issue_month',
       'loan_issue_dayofweek'],
      dtype='object')

First 5 rows with new features:
       loan_issue_year  loan_issue_month  loan_issue_dayofweek
75220             2015                 1                     0
48955             2014                11                     2
44966             2015                 4                     6
13568             201

In [12]:

# For 'term', we can extract the number directly.
X_train['term'] = X_train['term'].str.replace(' months', '').astype(int)
X_test['term'] = X_test['term'].str.replace(' months', '').astype(int)

employment_map = {
    '< 1 year': 0.5,
    '1 year': 1,
    '2-5 years': 3.5,
    '6-9 years': 7.5,  # Midpoint of 6 and 9
    '10+ years': 10
}
X_train['yearsEmployment'] = X_train['yearsEmployment'].map(employment_map)
X_test['yearsEmployment'] = X_test['yearsEmployment'].map(employment_map)

grade_map = {
    'A1': 0, 'A2': 1, 'A3': 2,
    'B1': 3, 'B2': 4, 'B3': 5,
    'C1': 6, 'C2': 7, 'C3': 8,
    'D1': 9, 'D2': 10, 'D3': 11,
    'E1': 12, 'E2': 13, 'E3': 14
}
X_train['grade'] = X_train['grade'].map(grade_map)
X_test['grade'] = X_test['grade'].map(grade_map)


print("Ordinal encoding complete.")
print("X_train[['term', 'yearsEmployment', 'grade']].head():")
print(X_train[['term', 'yearsEmployment', 'grade']].head())
     

Ordinal encoding complete.
X_train[['term', 'yearsEmployment', 'grade']].head():
       term  yearsEmployment  grade
75220    36              7.5      4
48955    60              0.5      5
44966    60              1.0     13
13568    36             10.0      3
92727    36              3.5      0


In [13]:
from sklearn.preprocessing import OneHotEncoder

# --- Step 1: Identify the nominal columns to encode ---
nominal_cols = ['homeOwnership', 'purpose', 'residentialState']

# --- Step 2: Set up and fit the encoder ---
# handle_unknown='ignore' will prevent errors if a category in test data was not in train data.
# sparse_output=False ensures the output is a standard numpy array.
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit the encoder on the training data and transform it
X_train_ohe_array = ohe.fit_transform(X_train[nominal_cols])

# Transform the test data using the FITTED encoder
X_test_ohe_array = ohe.transform(X_test[nominal_cols])

# Create new DataFrames  ---
ohe_cols = ohe.get_feature_names_out(nominal_cols)

X_train_ohe = pd.DataFrame(X_train_ohe_array, columns=ohe_cols, index=X_train.index)
X_test_ohe = pd.DataFrame(X_test_ohe_array, columns=ohe_cols, index=X_test.index)


# --- Step 4: Combine with the main dataframes and drop the original columns ---
# Drop the original nominal columns
X_train = X_train.drop(columns=nominal_cols)
X_test = X_test.drop(columns=nominal_cols)

# Concatenate the new one-hot encoded columns
X_train = pd.concat([X_train, X_train_ohe], axis=1)
X_test = pd.concat([X_test, X_test_ohe], axis=1)

print("\nOne-Hot Encoding complete.")
print(f"Original shape of X_train: {X_train.shape}")
print("Number of columns added:", len(ohe_cols))
     


One-Hot Encoding complete.
Original shape of X_train: (80000, 44)
Number of columns added: 21


In [14]:

#encoding the Y , as for XGBoost we can't use strings
target_map = {
    'Current': 0,
    'Default': 1
}

# --- Step 2: Apply the mapping to both y_train and y_test ---
print("Encoding y_train...")
y_train = y_train.map(target_map)

print("Encoding y_test...")
y_test = y_test.map(target_map)

# --- Step 3: Verify the result ---
# It's always good practice to check your work.
print("\nVerification of y_train encoding:")
print(y_train.value_counts())

print("\nVerification of y_test encoding:")
print(y_test.value_counts())
    

Encoding y_train...
Encoding y_test...

Verification of y_train encoding:
loanStatus
0    72035
1     7965
Name: count, dtype: int64

Verification of y_test encoding:
loanStatus
0    17961
1     2039
Name: count, dtype: int64


In [15]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
     

In [16]:
numerical_features = [col for col in X_train.columns if X_train[col].nunique() > 2] # A simple way to get non-binary cols

scaler = StandardScaler()

# Fit on training data ONLY
scaler.fit(X_train[numerical_features])

# Transform both train and test data
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[numerical_features] = scaler.transform(X_train[numerical_features])
X_test_scaled[numerical_features] = scaler.transform(X_test[numerical_features])

print("Feature scaling complete.")

Feature scaling complete.


In [20]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from imblearn.over_sampling import SMOTE

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier



counts = y_train.value_counts()

scale_pos_weight = counts[0] / counts[1]

print(f"Target variable encoded. Calculated scale_pos_weight: {scale_pos_weight:.2f}\n")
#applyign smot to avoid imbalance
print("Applying SMOTE to the training data...")
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_scaled, y_train)

models = {
    # --- Models with built-in imbalance handling ---
    "Logistic Regression": LogisticRegression(random_state=42, max_iter=1000, class_weight='balanced'),
    "Random Forest": RandomForestClassifier(random_state=42, class_weight='balanced'),
    "XGBoost": XGBClassifier(random_state=42, scale_pos_weight=scale_pos_weight, use_label_encoder=False, eval_metric='logloss'),

    # --- Models without built-in imbalance handling (we expect lower recall) ---
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42),
    "K-Nearest Neighbors (KNN)": KNeighborsClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
}


for name, model in models.items():
    print(f"--- Training and Evaluating {name} ---")

    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)

    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("\nClassification Report:")

    print(classification_report(y_test, y_pred))
    print("-" * 50 + "\n")
     

Target variable encoded. Calculated scale_pos_weight: 9.04

Applying SMOTE to the training data...
--- Training and Evaluating Logistic Regression ---
Accuracy: 0.8397

Confusion Matrix:
[[15119  2842]
 [  364  1675]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.84      0.90     17961
           1       0.37      0.82      0.51      2039

    accuracy                           0.84     20000
   macro avg       0.67      0.83      0.71     20000
weighted avg       0.91      0.84      0.86     20000

--------------------------------------------------

--- Training and Evaluating Random Forest ---
Accuracy: 0.9204

Confusion Matrix:
[[17861   100]
 [ 1492   547]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.99      0.96     17961
           1       0.85      0.27      0.41      2039

    accuracy                           0.92     20000
   macro avg       0.88 

C:\Users\pingt\anacondanav\Lib\site-packages\xgboost\core.py:158: UserWarning: [02:03:11] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Accuracy: 0.8822

Confusion Matrix:
[[16116  1845]
 [  510  1529]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.90      0.93     17961
           1       0.45      0.75      0.56      2039

    accuracy                           0.88     20000
   macro avg       0.71      0.82      0.75     20000
weighted avg       0.92      0.88      0.89     20000

--------------------------------------------------

--- Training and Evaluating Gradient Boosting ---
Accuracy: 0.9311

Confusion Matrix:
[[17724   237]
 [ 1141   898]]

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.99      0.96     17961
           1       0.79      0.44      0.57      2039

    accuracy                           0.93     20000
   macro avg       0.87      0.71      0.76     20000
weighted avg       0.92      0.93      0.92     20000

--------------------------------------------------

--- Traini

C:\Users\pingt\anacondanav\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Accuracy: 0.9288

Confusion Matrix:
[[17631   330]
 [ 1093   946]]

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.98      0.96     17961
           1       0.74      0.46      0.57      2039

    accuracy                           0.93     20000
   macro avg       0.84      0.72      0.77     20000
weighted avg       0.92      0.93      0.92     20000

--------------------------------------------------

--- Training and Evaluating K-Nearest Neighbors (KNN) ---
Accuracy: 0.9158

Confusion Matrix:
[[17749   212]
 [ 1472   567]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.99      0.95     17961
           1       0.73      0.28      0.40      2039

    accuracy                           0.92     20000
   macro avg       0.83      0.63      0.68     20000
weighted avg       0.90      0.92      0.90     20000

--------------------------------------------------

--